#!/bin/bash -eu
# Copyright 2020 Canonical Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors:
#  - edward.hope-morley@canonical.com

# Checks to see if Ceph backend is used in either Nova or Cinder and if it
# is, checks that all images in Glance have disk_format=raw.
# See the following KB article for information on why this is important:
# https://support.canonical.com/ua/s/article/openstack-boot-image-considerations

rc=0
ftmp=`mktemp`

exists="`juju status --format=json| jq '.applications| to_entries[]| select(.value.charm| test(\".+ceph-mon.+\"))'`"
if [ -z "$exists" ]; then
    echo "INFO: no ceph-mon found - skipping test"
    rm $ftmp
    exit 0
fi

juju status ceph-mon --format=json > $ftmp
readarray -t clients<<<"`jq -r '.applications."ceph-mon".relations.client[]' $ftmp`"
if ((${#clients[@]})) && [ -n "${clients[0]}" ]; then
    raw_required=false
    for client in ${clients[@]}; do
        if [[ $client =~ nova-compute.* ]] ||
               [[ $client =~ cinder-ceph.* ]]; then
            raw_required=true
            break
        fi
    done
    if $raw_required; then
        openstack image list --long -c ID -c 'Disk Format' -f value > $ftmp
        num_images=`awk '{print $2}' $ftmp| sort -u| wc -l`
        if ((num_images > 1)) || ((num_images == 1)) && [[ "`awk '{print $2}' $ftmp| sort -u`" != raw ]]; then
cat << EOF
WARNING: not all images in Glance have disk_format=raw

Your environment is using Ceph as a backend for one or both of nova-compute
or cinder and as a result it is essential to use images with raw format in
order to avoid a large capacity and performance impact on your cloud and ceph
cluster. This format is also needed in order to benefit from Copy-on-Write
cloning of images in both Cinder and Nova.

For more information on why this is important please see the following article:

https://support.canonical.com/ua/s/article/openstack-boot-image-considerations
EOF
            echo -e "\nImage format details:"
            readarray -t formats<<<"`sort -k 2 $ftmp| awk '{print $2}'| uniq`"
            for fmt in ${formats[@]}; do
                awk "\$2==\"$fmt\" {print \$2}" $ftmp| sort| uniq -c
            done
            echo ""
            rc=1
        fi
    else
        echo "No hard requirement for raw images - skipping check"
    fi
fi

rm $ftmp
exit $rc

